services:
  qmk-docker-keyball:
    image: archlinux:latest
    platform: linux/amd64
    restart: no
    build: .
    container_name: 'qmk-docker-keyball'
    working_dir: '/root/qmk'
    tty: true
    stdin_open: true
    volumes:
      - .:/root/opt

