services:
  qmk-docker-keyball:
    image: archlinux:latest
    # Confirm that M1 (arm64) can build the firmware
    platform: linux/amd64
    restart: 'always'
    build: .
    container_name: 'qmk-docker-keyball'
    working_dir: '/root/qmk'
    tty: true
    stdin_open: true
    volumes:
      - .:/root/opt

